apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: NodePort
  ports:
  - port: 83
    targetPort: 83
    nodePort: 30007
  selector:
    app: netflix-app
