apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer  # This is the key change to expose it with LoadBalancer
  ports:
  - port: 83
    targetPort: 80  # The container port where Netflix is running
  selector:
    app: netflix-app

